language: node_js
node_js:
- 7.3.0
notifications:
  email: false
services:
- docker
env:
  global:
  - DOCKER_REPOSITORY=ssense/ui-editorial
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: gZBHNEhXg/UpaMO/c7yyjyhdnD6yYnvpacS3hg/2GhWOQoyYbAVF2OXhgjAUC6+R9qtCOoWZA4hYLOTEryJgr3Veo8DY2z8OWZ2Go0U5LljAedGsBElwKvTv7RivvefactRbM/Ra8ilFISEkqPkFE/KIJfFHS0NfBq+ZTOVqFhbw7qpGHLsEwga/4Ej+264waFxkPZx/ntP8UkvE7MB+8iaWzZ9ukXUGZKFABwZwQsYfYbplhglMjecn6StocUUB5BnCkf7+4bLttPYQdlAsWqD0dNAKQyxaofYaCoi5pzNtcyPQcOKnkSawKrVQuQF6d7fjHchA2GY2KNP5AhXsEBkPSIrxgoVj6G8WgLr6aQj2n4QtSw/YCy6fbcA793MLDC7yOzjTlNCTS7cZbhbl4soUGb1DKQwZ7MYx3P2+6PJrIqz7iDeaNd3XE7V4QS8zBBUM9xv4UjqrmrqK+fzXn9eHp7Ctx10ELJnGFRzP6s5Ipubhbsee6jCKT0cVb/CE3WJprQnSvUavEN3vqEJTtYX1jjROhVt1aC/gIfFyCl/HcJzNrpThaF1BZiE4HqgYSuL6pN+mTMD9xGBam9VtjbE4r1cEgAi0gNeMsySUXiOsS2J3GE6sUW+Ta2H8QNJbPOtCLRiRQcAxYCApgnM9Ls70P2vukMrT7uw8aatwwxU=
  - secure: OdE2IDOMMaa4xy4fbnfmakO+X8sSDPKegD08F1DqwuHwJMQUN3gTpkmRrQNxv9ygc106VDhRYHK+ZlE9sJV2qaTlj+X/MNuHNeG/3KkoY59ZtGT5x3xy/oqZ7wxRjykHM3mBwCg1cHWzs2mDJEt+oyzUBB8v/IrRnkjt7uyWom9AgMytL8KMzZZT3dSZtzMlZCGP3tAvv0Ltqdvszxl1UhTqcdldgViFPqtq5fCULLAwjtR+EzbV5I1Yjhc77eTly551pRn9CEtN4i3CRuzkob6yqOTwXgMrVb6zVjZsBYbVW0Gi5PmWEiwBOIJngtpdHlKPEirM9Kn6ULowivDLVcVO3oij4lUUyl4AFfv66RtZeuJ7bKFSKqcJEBJfIu5wmdG4atI0VTVOkZ4agL+dhnYQTVF3iCr0wXcUVpN34woeH0NDw/EAeYCLuAEUTHi3qbgCiejklH+ZpZvqrVPGRA7ouTmmlUFK0TodvXfcbH5CXfXGYXNb0aHeipP3nPoijPgSSzaMLIwhzvMuKE7KA+9MR+pQx+f1PVQiqlf6YK7h4p1+Jv9L0CntwJltTmMLIJwaBJBODrgltW7Ruh6ESGzvgdB+Cv+cvPnsVFVCtKJmtbPtF9KS3DDxwcMvvIrwwZND1wsdD/dvkdvpYZ5hJAQW/RSf9wgwXLfjMjy8ZcM=
  - secure: OpRI76WZt32A5AFfAD4BY6T9SGQB1fmG0U6oMoHfSjlf1NuyhQbbShmJxnSjYz0HgWrkAUcVBb7lSiK0CK0kuZB1eLGNW88q65X40fF9+lcnw4qd8kcUYstpSaHiJbB8K+OMhKVhDwTOHwE2Phv5TgQRFgz6jYY+OmNva9Kdn36B8RJAIvDTz3rjPCtLNP0M6KBDzuzY6u4BDbUU0Y5z/pmQqE8LE2d0ly+IPkCez+wVY27ZsWytPkEx+SDVx4AyiGwI5PJnU9lqC7rhJQkEKiAP6PFUq3maqbk3+07WhQe+/ZAW7uN+mJjICv/QJeO1AtGxBbssTOg6b19KRM4kxNGzk6Mnp0HztGFnuTb9N6GT1tFej2wNRNwDjarctbmBuJzsu4ZmmUMmvnQas9vQV7JUYbiCzqynRT+XvP7dr09VkMaKTv4fusXXh8QyGz19GjEs5Pzzt66sFh7Pvpz3EsLDZ8xK2gqT50l8hzxKbleSehP3fAhjPhIvGkFK49SWSAgtUpYLmSebWr6/NTBLcgBosi0MXjbtQdPFhlDErvEXcYkQSLx0j2NdgK13yM/jLXeKyQ9c3TpzsEnu810WBncS5crUruagcNSOViOfpAwADrvi6CkiQvWxjKXq0mVQR3L3HzKqZ/khK+hXiYdLZmBdQ6HdGgaPuObXfWufAy4=
cache:
  directories:
  - "/home/travis/docker/"
before_install:
- docker --version
- echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
- npm install
script:
- NODE_ENV=production npm run build
- docker build -t ${DOCKER_REPOSITORY}:${COMMIT} .
- docker tag ${DOCKER_REPOSITORY}:${COMMIT} ${DOCKER_REPOSITORY}:latest
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push ${DOCKER_REPOSITORY}
